services:
    nginx-unit:
        container_name: nginx-unit
        build: ./containers/local/nginx_unit
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/html
            - ./containers/local/nginx_unit/config/config.json:/docker-entrypoint.d/config.json
        links:
            - mysql
        depends_on:
            - mysql
        networks:
            test-project:
                ipv4_address: 192.168.218.13

    mysql:
        image: mysql:8.4
        container_name: mysql_container
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - test-project

volumes:
    mysql_data:
        driver: local

networks:
    test-project:
        driver: bridge
        enable_ipv6: false
        ipam:
            driver: default
            config:
                -   subnet: 192.168.218.0/24
